package br.com.mobicare.cielo.webView.utils

const val URL_PARAM = "url"
const val IS_FROM_INTERNAL_FLOW = "isFromInternalFlow"
const val FLOW_NAME_PARAM = "flowName"
const val BEARER = "Bearer"
const val ACCESS_TOKEN = "access_token"
const val AUTHORIZATION = "authorization"
const val APP_BUILD = "app_buildversion"
const val DEBUG = "1"
const val PRD = "2"
const val OS = "os"
const val ANDROID = "android"
const val APP_RELEASE_VERSION = "app_releaseversion"
const val USERNAME = "username"
const val EMAIL = "email"
const val CPF = "cpf"
const val MAIN_ROLE = "mainrole"
const val EC_TRADING_NAME = "ec_tradingname"
const val EC_CNPJ = "ec_cnpj"
const val EC_CNPJ_ROOT = "ec_cnpj_root"
const val EC_HIERARCHY_LEVEL = "ec_hierarchylevel"
const val EC_ID = "ec_id"
const val EC_NAME = "ec_name"
const val EC_RECEIVABLE_TYPE = "ec_receivabletype"
const val DEVICE_MODEL = "device_model"