{
  "formatVersion": "1.1",
  "component": {
    "group": "com.discover.sdk",
    "module": "core",
    "version": "COR1.1.4-releaseCandidate",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "cpat4iaxdrhzzbisgs4kci6o7q"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "strictly": "1.20",
            "requires": "1.20"
          },
          "reason": "Fixed security issues: CVE-2018-11771"
        }
      ],
      "files": [
        {
          "name": "core-COR1.1.4-releaseCandidate.aar",
          "url": "core-COR1.1.4-releaseCandidate.aar",
          "size": 115196,
          "sha512": "d8fda1bb4304e406a6fbcf2b8fa618932bdf2ba82e27710f5518817fd42f4b72728e34da10f338a70214fdce34cf79e8f59bf32261ab1a69820ec7604c09ffbc",
          "sha256": "9bc0b5532649f507f99200671c52c527dbb77488983ee1b7b43e9bd41d38ca5e",
          "sha1": "b77085dab691df5533d741732cf81b94f58fddd5",
          "md5": "1d297dac1550e8145b0cf58ab72c4d67"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "core-COR1.1.4-releaseCandidate.aar",
          "url": "core-COR1.1.4-releaseCandidate.aar",
          "size": 115196,
          "sha512": "d8fda1bb4304e406a6fbcf2b8fa618932bdf2ba82e27710f5518817fd42f4b72728e34da10f338a70214fdce34cf79e8f59bf32261ab1a69820ec7604c09ffbc",
          "sha256": "9bc0b5532649f507f99200671c52c527dbb77488983ee1b7b43e9bd41d38ca5e",
          "sha1": "b77085dab691df5533d741732cf81b94f58fddd5",
          "md5": "1d297dac1550e8145b0cf58ab72c4d67"
        }
      ]
    }
  ]
}
