package br.com.mobicare.cielo.pix.domain

import android.os.Parcelable
import androidx.annotation.Keep
import kotlinx.android.parcel.Parcelize

@Keep
@Parcelize
data class QRCodeDecodeResponse(
    val abatement: Double? = null,
    val accountNumber: String? = null,
    val accountType: String? = null,
    val additionalData: String? = null,
    val address: String? = null,
    val branch: String? = null,
    val category: String? = null,
    val changeAmount: Double? = null,
    val city: String? = null,
    val creationDate: String? = null,
    val daysAfterDueDate: Int? = null,
    val decodeDate: String? = null,
    val description: String? = null,
    val discount: Double? = null,
    val dueDate: String? = null,
    val endToEndId: String? = null,
    val expireDate: String? = null,
    val finalAmount: Double? = null,
    val idTx: String? = null,
    val interest: Double? = null,
    val ispbChange: String? = null,
    val ispbChangeName: String? = null,
    val ispbWithDraw: String? = null,
    val ispbWithDrawName: String? = null,
    val key: String? = null,
    val keyType: String? = null,
    val modalityAltChange: String? = null,
    val modalityAltWithDraw: String? = null,
    val modalityAlteration: String? = null,
    val modalityChangeAgent: String? = null,
    val modalityWithDrawAgent: String? = null,
    val originalAmount: Double? = null,
    val participant: Int? = null,
    val participantName: String? = null,
    val payerDocument: String? = null,
    val payerName: String? = null,
    val payerType: String? = null,
    val penalty: Double? = null,
    val pixType: String? = null,
    val qrCode: String? = null,
    val receiverDocument: String? = null,
    val receiverName: String? = null,
    val receiverPersonType: String? = null,
    val receiverTradingName: String? = null,
    val reusable: Boolean,
    val revision: Int? = null,
    val state: String? = null,
    val status: Int? = null,
    val type: String? = null,
    val url: String? = null,
    val value: Double? = null,
    val withDrawAmount: Double? = null,
    val zipCode: String? = null,
    val isSchedulable: Boolean? = null
) : Parcelable