package br.com.mobicare.cielo.meusrecebimentosnew.enums

enum class MeusRecebimentosCodigosEnum(val code: Int) {
    RECEBIVEIS_VENDA(1),
    VALORES_ATENCIPADOS(2),
    CREDITOS_ATENCIPACAO(3),
    CANCELAMENTOS(4),
    CONTESTACOES(5),
    COBRANCA_ALUGUEL(6),
    OUTRAS_COBRANCAS(7),
    OUTROS_VALORES_RECEBIDOS(8),
    CREDITO_GRAVAME(10),
    CREDITO_CESSAO(11),
    DEBITO_GRAVAME(12),
    DEBITO_CESSAO(13),
    LIBERACAO_SALDO_RETIDO(96),
    CREDITO_DE_ANTECIPACAO(98),
    VALORES_JA_ANTECIPADOS(99),
    VALORES_PENDENTES(100),
    VALORES_PENDENTES_RECEBIVEIS_VENDA(VALORES_PENDENTES.code + RECEBIVEIS_VENDA.code),
    VALORES_PENDENTES_CANCELAMENTOS(VALORES_PENDENTES.code + CANCELAMENTOS.code),
    VALORES_PENDENTES_CONTESTACOES(VALORES_PENDENTES.code + CONTESTACOES.code),
    VALORES_PENDENTES_OUTRAS_COBRANCAS(VALORES_PENDENTES.code + OUTRAS_COBRANCAS.code),
    VALORES_PENDENTES_OUTROS_VALORES_RECEBIDOS(VALORES_PENDENTES.code + OUTROS_VALORES_RECEBIDOS.code),
    VALORES_PENDENTES_LIBERACAO_SALDO_RETIDO(VALORES_PENDENTES.code + LIBERACAO_SALDO_RETIDO.code);

    companion object {
        fun valueOf(value: Int) = values().find { it.code == value }
    }
}