{
  "formatVersion": "1.1",
  "component": {
    "group": "com.discover.sdk",
    "module": "card-reader",
    "version": "TOOK2.3.2-releaseCandidate",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "4yhubwsr6bdzdprugr7c44chd4"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.discover.sdk",
          "module": "core",
          "version": {
            "requires": "COR1.1.4-releaseCandidate"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "strictly": "1.20",
            "requires": "1.20"
          },
          "reason": "Fixed security issues: CVE-2018-11771"
        }
      ],
      "files": [
        {
          "name": "card-reader-TOOK2.3.2-releaseCandidate.aar",
          "url": "card-reader-TOOK2.3.2-releaseCandidate.aar",
          "size": 824421,
          "sha512": "b5097ec89364a1ae5b2bcbfaf691fb4151c44664733950946a730cccf8ea5153ff57bfea0e9ddb26358e396ba1af0cd20f917d117661c4f2ba5f23093b159f66",
          "sha256": "e00a8f3facbc26a0cabd557a19d32244f06e53d946714a5e161f401e2ee1d1cb",
          "sha1": "fd37dc074e518686e6ed5a9a8278e590a1364327",
          "md5": "1aacae8f115e6f19b67aff6ab2d83043"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.discover.sdk",
          "module": "core",
          "version": {
            "requires": "COR1.1.4-releaseCandidate"
          }
        }
      ],
      "files": [
        {
          "name": "card-reader-TOOK2.3.2-releaseCandidate.aar",
          "url": "card-reader-TOOK2.3.2-releaseCandidate.aar",
          "size": 824421,
          "sha512": "b5097ec89364a1ae5b2bcbfaf691fb4151c44664733950946a730cccf8ea5153ff57bfea0e9ddb26358e396ba1af0cd20f917d117661c4f2ba5f23093b159f66",
          "sha256": "e00a8f3facbc26a0cabd557a19d32244f06e53d946714a5e161f401e2ee1d1cb",
          "sha1": "fd37dc074e518686e6ed5a9a8278e590a1364327",
          "md5": "1aacae8f115e6f19b67aff6ab2d83043"
        }
      ]
    }
  ]
}
