package br.com.mobicare.cielo.tapOnPhone.utils

object TapOnPhoneConstants {
    const val REFERENCE_TAP_ON_PHONE = "TAP-ON-PHONE"
    const val REFERENCE_RECEBA_RAPIDO = "RECEBA_RAPIDO"

    const val TAP_ON_PHONE_ACTIVITY_WAS_OPENED_BY_POS_VIRTUAL_ARGS = "TAP_ON_PHONE_ACTIVITY_WAS_OPENED_BY_POS_VIRTUAL_ARGS"
    const val TAP_ON_PHONE_HAS_CARD_READER_ARGS = "TAP_ON_PHONE_HAS_CARD_READER_ARGS"
    const val CARD_READER_NOT_CONNECT = -2
    const val ERROR_CODE_FORTY_TWO_IN_MAKE_TRANSACTION = 42
}
