package br.com.mobicare.cielo.commons.utils.financial

class Bank {

    companion object {

        fun nameFrom(code: String): String {
            val bankName: String
            when (code) {
                "246" -> bankName = "Banco ABC Brasil S.A.";
                "075" -> bankName = "Banco ABN AMRO S.A."
                "025" -> bankName = "Banco Alfa S.A."
                "641" -> bankName = "Banco Alvorada S.A."
                "065" -> bankName = "Banco Andbank (Brasil) S.A."
                "024" -> bankName = "Banco BANDEPE S.A."
                "740" -> bankName = "Banco Barclays S.A."
                "107" -> bankName = "Banco BBM S.A."
                "096" -> bankName = "Banco BM&FBOVESPA de Serviços de Liquidação e Custódia S.A"
                "318" -> bankName = "Banco BMG S.A."
                "752" -> bankName = "Banco BNP Paribas Brasil S.A."
                "248" -> bankName = "Banco Boavista Interatlântico S.A."
                "218" -> bankName = "Banco Bonsucesso S.A."
                "063" -> bankName = "Banco Bradescard S.A."
                "036" -> bankName = "Banco Bradesco BBI S.A."
                "204" -> bankName = "Banco Bradesco Cartões S.A."
                "394" -> bankName = "Banco Bradesco Financiamentos S.A."
                "237" -> bankName = "Banco Bradesco S.A."
                "208" -> bankName = "Banco BTG Pactual S.A."
                "263" -> bankName = "Banco Cacique S.A."
                "473" -> bankName = "Banco Caixa Geral - Brasil S.A."
                "040" -> bankName = "Banco Cargill S.A."
                "739" -> bankName = "Banco Cetelem S.A."
                "233" -> bankName = "Banco Cifra S.A."
                "745" -> bankName = "Banco Citibank S.A."
                "000" -> bankName = "Banco CNH Industrial Capital S.A."
                "095" -> bankName = "Banco Confidence de Câmbio S.A."
                "756" -> bankName = "Banco Cooperativo do Brasil S.A. - BANCOOB"
                "748" -> bankName = "Banco Cooperativo Sicredi S.A."
                "222" -> bankName = "Banco Credit Agricole Brasil S.A."
                "505" -> bankName = "Banco Credit Suisse (Brasil) S.A."
                "003" -> bankName = "Banco da Amazônia S.A."
                "083" -> bankName = "Banco da China Brasil S.A."
                "707" -> bankName = "Banco Daycoval S.A."
                "456" -> bankName = "Banco de Tokyo-Mitsubishi UFJ Brasil S.A."
                "001" -> bankName = "Banco do Brasil S.A."
                "047" -> bankName = "Banco do Estado de Sergipe S.A."
                "037" -> bankName = "Banco do Estado do Pará S.A."
                "041" -> bankName = "Banco do Estado do Rio Grande do Sul S.A."
                "004" -> bankName = "Banco do Nordeste do Brasil S.A."
                "265" -> bankName = "Banco Fator S.A."
                "224" -> bankName = "Banco Fibra S.A."
                "626" -> bankName = "Banco Ficsa S.A."
                "612" -> bankName = "Banco Guanabara S.A."
                "012" -> bankName = "Banco INBURSA de Investimentos S.A."
                "604" -> bankName = "Banco Industrial do Brasil S.A."
                "653" -> bankName = "Banco Indusval S.A."
                "249" -> bankName = "Banco Investcred Unibanco S.A."
                "184" -> bankName = "Banco Itaú BBA S.A."
                "029" -> bankName = "Banco Itaú BMG Consignado S.A."
                "479" -> bankName = "Banco ItaúBank S.A"
                "376" -> bankName = "Banco J. P. Morgan S.A."
                "074" -> bankName = "Banco J. Safra S.A."
                "217" -> bankName = "Banco John Deere S.A."
                "600" -> bankName = "Banco Luso Brasileiro S.A."
                "389" -> bankName = "Banco Mercantil do Brasil S.A."
                "370" -> bankName = "Banco Mizuho do Brasil S.A."
                "746" -> bankName = "Banco Modal S.A."
                "212" -> bankName = "Banco Original S.A."
                "623" -> bankName = "Banco PAN S.A."
                "611" -> bankName = "Banco Paulista S.A."
                "094" -> bankName = "Banco Petra S.A."
                "643" -> bankName = "Banco Pine S.A."
                "747" -> bankName = "Banco Rabobank International Brasil S.A."
                "633" -> bankName = "Banco Rendimento S.A."
                "120" -> bankName = "Banco Rodobens S.A."
                "422" -> bankName = "Banco Safra S.A."
                "033" -> bankName = "Banco Santander (Brasil) S.A."
                "366" -> bankName = "Banco Société Générale Brasil S.A."
                "464" -> bankName = "Banco Sumitomo Mitsui Brasileiro S.A."
                "082" -> bankName = "Banco Topázio S.A."
                "634" -> bankName = "Banco Triângulo S.A."
                "655" -> bankName = "Banco Votorantim S.A."
                "610" -> bankName = "Banco VR S.A."
                "119" -> bankName = "Banco Western Union do Brasil S.A."
                "021" -> bankName = "BANESTES S.A. Banco do Estado do Espírito Santo"
                "719" -> bankName = "Banif-Banco Internacional do Funchal (Brasil)S.A."
                "755" -> bankName = "Bank of America Merrill Lynch Banco Múltiplo S.A."
                "081" -> bankName = "BBN Banco Brasileiro de Negócios S.A."
                "250" -> bankName = "BCV - Banco de Crédito e Varejo S.A."
                "017" -> bankName = "BNY Mellon Banco S.A."
                "069" -> bankName = "BPN Brasil Banco Múltiplo S.A."
                "125" -> bankName = "Brasil Plural S.A. - Banco Múltiplo"
                "070" -> bankName = "BRB - Banco de Brasília S.A."
                "104" -> bankName = "Caixa Econômica Federal"
                "320" -> bankName = "China Construction Bank (Brasil) Banco Múltiplo S.A."
                "477" -> bankName = "Citibank N.A."
                "487" -> bankName = "Deutsche Bank S.A. - Banco Alemão"
                "064" -> bankName = "Goldman Sachs do Brasil Banco Múltiplo S.A."
                "078" -> bankName = "Haitong Banco de Investimento do Brasil S.A."
                "062" -> bankName = "Hipercard Banco Múltiplo S.A."
                "399" -> bankName = "HSBC Bank Brasil S.A. - Banco Múltiplo"
                "492" -> bankName = "ING Bank N.V."
                "652" -> bankName = "Itaú Unibanco Holding S.A."
                "341" -> bankName = "Itaú Unibanco S.A."
                "488" -> bankName = "JPMorgan Chase Bank, National Association"
                "128" -> bankName = "MSB Bank S.A. Banco de Câmbio"
                "254" -> bankName = "Paraná Banco S.A."
                "751" -> bankName = "Scotiabank Brasil S.A. Banco Múltiplo"
                "118" -> bankName = "Standard Chartered Bank (Brasil) S/A–Bco Invest."
                "129" -> bankName = "UBS Brasil Banco de Investimento S.A."
                else -> bankName = "Banco Desconhecido."

            }

            return bankName
        }
    }
}