{
  "formatVersion": "1.1",
  "component": {
    "group": "com.discover.sdk",
    "module": "card-reader",
    "version": "TOOK2.3.2-release",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "4yhubwsr6bdzdprugr7c44chd4"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.discover.sdk",
          "module": "core",
          "version": {
            "requires": "COR1.1.4-release"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "strictly": "1.20",
            "requires": "1.20"
          },
          "reason": "Fixed security issues: CVE-2018-11771"
        }
      ],
      "files": [
        {
          "name": "card-reader-TOOK2.3.2-release.aar",
          "url": "card-reader-TOOK2.3.2-release.aar",
          "size": 688774,
          "sha512": "014ea090f365867aa664525f5f991d840d05d9182ad23766d4f1005b700e01b26a07a22e1610f9cbbb18d54aba06da5862783e2770861adae47cf58f7b4e00ff",
          "sha256": "eca27633c06bbe15c0844fb50f7b78995493b310b58e7049c40623e7e134fc65",
          "sha1": "2c73abf2ff49e8c656f773945fe88155df327a86",
          "md5": "0249e3e5dd110120174663a9869d5262"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.discover.sdk",
          "module": "core",
          "version": {
            "requires": "COR1.1.4-release"
          }
        }
      ],
      "files": [
        {
          "name": "card-reader-TOOK2.3.2-release.aar",
          "url": "card-reader-TOOK2.3.2-release.aar",
          "size": 688774,
          "sha512": "014ea090f365867aa664525f5f991d840d05d9182ad23766d4f1005b700e01b26a07a22e1610f9cbbb18d54aba06da5862783e2770861adae47cf58f7b4e00ff",
          "sha256": "eca27633c06bbe15c0844fb50f7b78995493b310b58e7049c40623e7e134fc65",
          "sha1": "2c73abf2ff49e8c656f773945fe88155df327a86",
          "md5": "0249e3e5dd110120174663a9869d5262"
        }
      ]
    }
  ]
}
