package br.com.mobicare.cielo.arv.utils

object ArvConstants {

    const val ARV_ANTICIPATION = "arvAnticipation"

    const val CLOSED_MARKET = "CLOSED_MARKET"
    const val CORPORATE_DESK = "CORPORATE_DESK"
    const val MERCHANT_NOT_ELIGIBLE = "MERCHANT_NOT_ELIGIBLE"
    const val INVALID_RECEIVABLE_AMOUNT = "INVALID_RECEIVABLE_AMOUNT"
    const val NONEXISTENT_RECEIVABLES_ANTICIPATION = "NONEXISTENT_RECEIVABLES_ANTICIPATION"

    const val USER_VIEW_ARV_ONBOARDING = "USER_VIEW_ARV_ONBOARDING"

    const val CIELO_NEGOTIATION_TYPE = "CIELO"
    const val MARKET_NEGOTIATION_TYPE = "MARKET"
    const val BOTH_NEGOTIATION_TYPE = "BOTH"

    const val POINT_OF_SALE = "POINT_OF_SALE"

    const val ARV_HISTORIC_DETAILS_NEGOTIATION_ARGS = "ARV_HISTORIC_DETAILS_NEGOTIATION_ARGS"

    const val SIMULATION_TYPE_VALUE = "Valor"
}
