{
  "formatVersion": "1.1",
  "component": {
    "group": "com.discover.sdk",
    "module": "core",
    "version": "COR1.1.4-release",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "cpat4iaxdrhzzbisgs4kci6o7q"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "strictly": "1.20",
            "requires": "1.20"
          },
          "reason": "Fixed security issues: CVE-2018-11771"
        }
      ],
      "files": [
        {
          "name": "core-COR1.1.4-release.aar",
          "url": "core-COR1.1.4-release.aar",
          "size": 110543,
          "sha512": "4e6f0728528f9a5017b939668bcb30349b12857cca6a0e7e5dfe5501650926761a46a9e91e7cdee682b760496c17fe6d5ae9ccba1e6b78f92f7bf0128a362fb4",
          "sha256": "4856a3e1f6660f133a57150ec46178a222226e8b6b39bac8172c57b300fb1d33",
          "sha1": "81409863be97208187af54e944250d7d5177498e",
          "md5": "061bc6f4b0173d2a92118aadf79086b5"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "core-COR1.1.4-release.aar",
          "url": "core-COR1.1.4-release.aar",
          "size": 110543,
          "sha512": "4e6f0728528f9a5017b939668bcb30349b12857cca6a0e7e5dfe5501650926761a46a9e91e7cdee682b760496c17fe6d5ae9ccba1e6b78f92f7bf0128a362fb4",
          "sha256": "4856a3e1f6660f133a57150ec46178a222226e8b6b39bac8172c57b300fb1d33",
          "sha1": "81409863be97208187af54e944250d7d5177498e",
          "md5": "061bc6f4b0173d2a92118aadf79086b5"
        }
      ]
    }
  ]
}
