package br.com.mobicare.cielo.pix.constants

const val PIX_USAGE_TERMS_URL = "https://www.cielo.com.br/pix/termo-de-uso/"
const val PIX_PARTNER_USAGE_TERMS_URL =
    "https://minhaconta2.cielo.com.br/assets/termo_pix_bancos.pdf"

const val ALREADY_ENABLED = "ALREADY_ENABLED"
const val IN_PROGRESS = "IN_PROGRESS"
const val INCOMPATIBLE_SOLUTION = "INCOMPATIBLE_SOLUTION"
const val DOMICELE_NOT_ELIGIBLE = "DOMICELE_NOT_ELEGIBILE"
const val MERCHANT_UNALLOWED = "MERCHANT_UNALLOWED"
const val PAYMENT_BLOCKING = "PAYMENT_BLOCKING"
const val DIGITAL_ACCOUNT = "DIGITAL_ACCOUNT"
const val ACCOUNT_INVALID = "ACCOUNT_INVALID"
const val RESTRICTED_LARGE_ACCOUNT = "RESTRICTED_LARGE_ACCOUNT"

const val ALREADY_ENABLED_PIX_PARTNER = "ALREADY_ENABLED_PIX_PARTNER"
const val IN_PROGRESS_PIX_PARTNER = "IN_PROGRESS_PIX_PARTNER"
const val INCOMPATIBLE_SOLUTION_PIX_PARTNER = "INCOMPATIBLE_SOLUTION_PIX_PARTNER"
const val DOMICELE_NOT_ELIGIBLE_PIX_PARTNER = "DOMICELE_NOT_ELEGIBILE_PIX_PARTNER"
const val MERCHANT_UNALLOWED_PIX_PARTNER = "MERCHANT_UNALLOWED_PIX_PARTNER"
const val PAYMENT_BLOCKING_PIX_PARTNER = "PAYMENT_BLOCKING_PIX_PARTNER"

const val WAITING_ACTIVATION = "WAITING_ACTIVATION"
const val ACTIVE = "ACTIVE"
const val PENDING = "PENDING"
const val CIELO = "CIELO"
const val PARTNER = "PARTNER"

const val PIX_DATA_QUERY_ARGS = "PIX_DATA_QUERY_ARGS"
const val IS_PARTNER_ARGS = "IS_PARTNER_ARGS"
const val IS_SHOW_DATA_QUERY_ARGS = "IS_SHOW_DATA_QUERY_ARGS"
const val TRANSITORY_ACCOUNT = "TRANSITORY_ACCOUNT"
const val PREPAID_RESPONSE_ARGS = "PREPAID_RESPONSE_ARGS"
const val PIX_REDIRECT_RANDOM_KEY = "PIX_REDIRECT_RANDOM_KEY"
const val PIX_REDIRECT_MAIN_KEY_DETAILS = "PIX_REDIRECT_MAIN_KEY_DETAILS"
const val PIX_MASTER_KEY_ARGS = "PIX_MASTER_KEY_ARGS"
const val PIX_TYPE_KEY_ARGS = "PIX_TYPE_KEY_ARGS"
const val PIX_TYPE_KEY_VALUE_ARGS = "PIX_TYPE_KEY_VALUE_ARGS"
const val PIX_KEY_INFORMATION_ARGS = "PIX_KEY_INFORMATION_ARGS"
const val PIX_BALANCE_ARGS = "PIX_BALANCE_ARGS"
const val PIX_FROM_COPY_PASTE_ARGS = "PIX_FROM_COPY_PASTE_ARGS"
const val PIX_AMOUNT_ARGS = "PIX_AMOUNT_ARGS"
const val PIX_INPUT_KEY_ARGS = "PIX_INPUT_KEY_ARGS"
const val PIX_LIST_KEY_TYPE_ARGS = "PIX_LIST_KEY_TYPE_ARGS"
const val PIX_LIST_KEY_TYPE_TITLE_ARGS = "PIX_LIST_KEY_TYPE_TITLE_ARGS"
const val PIX_MY_KEY_DETAILS = "PIX_MY_KEY_DETAILS"
const val PIX_TRANSFER_DETAILS_RESPONSE_ARGS = "PIX_TRANSFER_DETAILS_RESPONSE_ARGS"
const val PIX_REVERSAL_RECEIPTS_RESPONSE_ARGS = "PIX_REVERSAL_RECEIPTS_RESPONSE_ARGS"
const val PIX_INPUT_KEY_CREATE_ARGS = "PIX_INPUT_KEY_CREATE_ARGS"
const val PIX_KEY_ARGS = "PIX_KEY_ARGS"
const val PIX_CLAIM_FLOW_ARGS = "PIX_CLAIM_FLOW_ARGS"
const val PIX_CLAIM_ID_ARGS = "PIX_CLAIM_ID_ARGS"
const val PIX_VALIDATION_CODE_VALUE_ARGS = "PIX_VALIDATION_CODE_VALUE_ARGS"
const val PIX_BANK_ARGS = "PIX_BANK_ARGS"
const val PIX_IDENTIFIER_QR_CODE_ARGS = "PIX_IDENTIFIER_QR_CODE_ARGS"
const val PIX_AMOUNT_QR_CODE_ARGS = "PIX_AMOUNT_QR_CODE_ARGS"
const val PIX_MY_KEYS_ARGS = "PIX_MY_KEYS_ARGS"
const val PIX_DECODE_QRCODE_ARGS = "PIX_DECODE_QRCODE_ARGS"
const val PIX_QR_CODE_CHARGE_DETAILS = "PIX_QR_CODE_CHARGE_DETAILS"
const val PIX_SELECTED_KEY_ARGS = "PIX_SELECTED_KEY_ARGS"
const val PIX_TITLE_AMOUNT_BS_ARGS = "PIX_TITLE_AMOUNT_BS_ARGS"
const val PIX_REVERSAL_AVAILABLE_BS_ARGS = "PIX_REVERSAL_AVAILABLE_BS_ARGS"
const val PIX_IS_DISMISS_BS_ARGS = "PIX_IS_DISMISS_BS_ARGS"
const val PIX_MESSAGE_AMOUNT_BS_ARGS = "PIX_MESSAGE_AMOUNT_BS_ARGS"
const val PIX_TEXT_BUTTON_AMOUNT_BS_ARGS = "PIX_TEXT_BUTTON_AMOUNT_BS_ARGS"
const val PIX_PAYEE_ARGS = "PIX_PAYEE_ARGS"
const val PIX_AGENCY_NUMBER_ARGS = "PIX_AGENCY_NUMBER_ARGS"
const val PIX_TRANSACTION_CODE_ARGS = "PIX_TRANSACTION_CODE_ARGS"
const val PIX_ID_END_TO_END_ARGS = "PIX_ID_END_TO_END_ARGS"
const val IS_HOME_PIX_ARGS = "IS_HOME_PIX_ARGS"
const val IS_POSSIBLE_CHANGE_PIX_ARGS = "IS_POSSIBLE_CHANGE_PIX_ARGS"
const val PIX_GO_BACK_TO_ARGS = "PIX_GO_BACK_TO_ARGS"
const val PIX_IS_TRUSTED_DESTINATION_ARGS = "PIX_IS_TRUSTED_DESTINATION_ARGS"
const val PIX_IS_KEY_ARGS = "PIX_IS_KEY_ARGS"
const val PIX_MY_LIMITS_IS_HOME_ARGS = "PIX_MY_LIMITS_IS_HOME_ARGS"
const val PIX_TRUSTED_DESTINATION_RESPONSE_ARGS = "PIX_TRUSTED_DESTINATION_RESPONSE_ARGS"
const val PIX_CONTACT_ADD_SUCCESS_ARGS = "PIX_CONTACT_ADD_SUCCESS_ARGS"
const val PIX_SHOW_DIALOG_ADD_NEW_RELIABLE_CONTACT_ARGS = "PIX_SHOW_DIALOG_ADD_NEW_RELIABLE_CONTACT_ARGS"
const val PIX_RETURN_FRAGMENT_WHEN_FINISHED_OPERATION = "PIX_RETURN_FRAGMENT_WHEN_FINISHED_OPERATION"

const val PIX_KEY = "PIX_KEY"
const val PIX_QR_CODE = "PIX_QR_CODE"
const val PIX_HOME = "PIX_HOME"
const val PIX_EXTRACT_RESPONSE_ARGS = "PIX_EXTRACT_RESPONSE_ARGS"
const val PIX_SCHEDULING_CODE_ARGS = "PIX_SCHEDULING_CODE_ARGS"
const val PIX_NULL_AMOUNT = "-"
const val REFRESH_EXTRACT_PAGE = "REFRESH_EXTRACT_PAGE"
const val PIX_EXTRACT_RECEIPT_ARGS = "PIX_EXTRACT_RECEIPT_ARGS"
const val PIX_IS_A_REVERSAL_TRANSACTION_ARGS = "PIX_IS_A_REVERSAL_TRANSACTION_ARGS"

const val PIX_BLOCK_BANK_DOMICILE = "BANK_DOMICILE"
const val PIX_BLOCK_PENNY_DROP = "PENNY_DROP"
const val PIX_IN_PROGRESS = "IN_PROGRESS"

const val SCREENSHOT = "images"
const val PNG = ".png"
const val AUTHORITY_PROVIDER = "br.com.mobicare.cielo.fileprovider"

const val EMPTY = ""
const val INTERNAL = "interno"
const val DEFAULT_BALANCE = "-1"
const val DEFAULT_OTP = "000000"

const val WITH_COUNTRY_CODE = "+"
const val COUNTRY_CODE = "+55"
const val KEY_EVP = "Chave aleatória"

const val KEY_NOT_FOUND = "KEY_NOT_FOUND"

const val RETURN_800 = 800
const val RETURN_801 = 801
const val RETURN_802 = 802
const val RETURN_805 = 805

const val TRANSFER = 0
const val READ_QR_CODE = 1
const val GENERATE_CHARGE = 2
const val COPY_AND_PASTE = 3

const val ANIMATION_TIME: Long = 2000
const val COUNTDOWN_TIME: Long = 60000
const val INTERVAL_TIME: Long = 1000

const val PIX_STATUS_APPROVED = "APPROVED"
const val PIX_STATUS_PENDING = "PENDING"
