package br.com.mobicare.cielo.posVirtual.utils

object PosVirtualConstants {

    const val REFERENCE_CODE_CIELO_TAP = "TAP-ON-PHONE"
    const val REFERENCE_CODE_SUPER_LINK = "SUPERLINK-ADDITIONAL"
    const val REFERENCE_CODE_QR_CODE_PIX = "PIX"
    const val REFERENCE_CODE_AUTOMATIC_RECEIPT = "RECEBA-RAPIDO"
    const val AUTOMATIC_RECEIPT = "RECEBA_RAPIDO"

    const val VISA_BRAND_CODE = "1"

    const val POS_VIRTUAL_ACCREDITATION_CREATE_ORDER_AUTHORIZED = "AUTHORIZED"
    const val POS_VIRTUAL_ACCREDITATION_CREATE_ORDER_BANK_ACCOUNT = "BANK_ACCOUNT"
    const val POS_VIRTUAL_ACCREDITATION_CREATE_ORDER_CHECKING = "CHECKING"

    const val POS_VIRTUAL_ERROR_CODE_NOT_ELIGIBLE = "NOT_ELIGIBLE"
    const val POS_VIRTUAL_ERROR_CODE_ACTIVITY_BRANCH = "ACTIVITY_BRANCH"
    const val POS_VIRTUAL_ERROR_CODE_SUSPECT_FOR_FRAUD = "SUSPECT_FOR_FRAUD"
    const val POS_VIRTUAL_ERROR_CODE_REQUIRED_DATA_FIELD = "REQUIRED_FIELDS"
    const val POS_VIRTUAL_ERROR_CODE_INVALID_BANK = "INVALID_BANK"
    const val POS_VIRTUAL_ERROR_CODE_TIME_OUT = "TIME_OUT"
    const val POS_VIRTUAL_ERROR_CODE_INVALID_AMOUNT = "INVALID_AMOUNT"
    const val POS_VIRTUAL_ERROR_CODE_INTEGRATION_ERROR = "INTEGRATION_ERROR"
    const val POS_VIRTUAL_ERROR_CODE_LIMIT_EXCEEDED = "LIMIT_EXCEEDED"
    const val POS_VIRTUAL_ERROR_CODE_PRODUCT_NOT_FOUND = "PRODUCT_NOT_FOUND"
    const val POS_VIRTUAL_ERROR_CODE_NOT_FOUND = "NOT_FOUND"

}