package br.com.mobicare.cielo.tapOnPhone.constants

const val COUNTRY_CODE: Short = 76

const val TOP_INSTALLMENTS_QUANTITY_ARGS = "TOP_INSTALLMENTS_QUANTITY_ARGS"
const val TOP_CURRENT_SELECTED_INSTALLMENT_ARGS = "TOP_CURRENT_SELECTED_INSTALLMENT_ARGS"

const val BRAZIL_MONEY_CURRENCY: Short = 986
const val INSTALLMENTS = "Installments"
const val INSTALLMENTS_TEXT = "InstallmentsText"

const val REQUIRED_FIELDS = "REQUIRED_FIELDS"

const val DEVICE_TAP_ARGS = "DEVICE_TAP_ARGS"
const val TOP_ELIGIBILITY_ARGS = "TOP_ELIGIBILITY_ARGS"

const val POS_VIRTUAL_FLOW_ARGS = "POS_VIRTUAL_FLOW_ARGS"