package br.com.mobicare.cielo.interactBannersOffersNew.utils.enums

import androidx.annotation.DrawableRes
import br.com.mobicare.cielo.R

enum class InteractBannerEnum(
    @DrawableRes val leaderboardResId: Int,
    @DrawableRes val rectangleResId: Int,
) {
    INTERACT_BANNER_OFFER_ARV(
        R.drawable.img_arv_leaderboard_banner,
        R.drawable.img_arv_rectangle_banner,
    ),
    INTERACT_BANNER_OFFER_RECEBA_MAIS(
        R.drawable.img_receba_mais_leaderboard_banner,
        R.drawable.img_receba_mais_rectangle_banner,
    ),
    INTERACT_BANNER_OFFER_RECEBA_RAPIDO(
        R.drawable.img_receba_rapido_leaderboard_banner,
        R.drawable.img_receba_rapido_rectangle_banner,
    ),
    INTERACT_BANNER_OFFER_BCREDI(
        R.drawable.img_bcredi_leaderboard_banner,
        R.drawable.img_bcredi_rectangle_banner,
    ),
    INTERACT_BANNER_OFFER_FLIP(
        R.drawable.img_flip_leaderboard_banner,
        R.drawable.img_flip_rectangle_banner,
    ),
    INTERACT_BANNER_OFFER_SUPER_LINK(
        R.drawable.img_superlink_leaderboard_banner,
        R.drawable.img_superlink_rectangle_banner,
    ),
    INTERACT_BANNER_OFFER_CIELO_PROMO(
        R.drawable.img_cielo_promo_leaderboard_banner,
        R.drawable.img_cielo_promo_rectangle_banner,
    ),
    INTERACT_BANNER_OFFER_TOKEN_CIELO(
        R.drawable.img_token_cielo_leaderboard_banner,
        R.drawable.img_token_cielo_rectangle_banner,
    ),
    INTERACT_BANNER_OFFER_TAXAS_E_PLANOS(
        R.drawable.img_receive_automatic_massiva_leaderboard_banner,
        R.drawable.img_receive_automatic_massiva_rectangle_banner,
    ),
    INTERACT_BANNER_RECEBA_RAPIDO_MASSIVA_CARENCIA(
        R.drawable.img_receba_rapido_massiva_carencia_leaderboard_banner,
        R.drawable.img_receba_rapido_massiva_carencia_rectangle_banner,
    ),
    INTERACT_BANNER_OFFER_FAROL(
        R.drawable.img_farol_leaderboard_banner,
        R.drawable.img_farol_rectangle_banner,
    ),
    INTERACT_BANNER_OFFER_PIX(
        R.drawable.img_pix_leaderboard_banner,
        R.drawable.img_pix_rectangle_banner,
    ),
    INTERACT_BANNER_OFFER_PIX_PARTNER(
        R.drawable.img_pix_partner_leaderboard_banner,
        R.drawable.img_pix_partner_rectangle_banner,
    ),
    INTERACT_BANNER_OFFER_CAIXA(
        R.drawable.img_caixa_leaderboard_banner,
        R.drawable.img_caixa_rectangle_banner,
    ),
    INTERACT_BANNER_OFFER_DEBIT(
        R.drawable.img_debt_negotiation_leaderboard_banner,
        R.drawable.img_debt_negotiation_rectangle_banner,
    ),
    CIELO_ACAO_SELIC_RR(
        R.drawable.img_cielo_acao_selic_rr,
        R.drawable.img_cielo_acao_selic_rr_rectangle,
    ),
    CIELO_ACAO_RR_SELIC_E_ITC_MASTER(
        R.drawable.img_cielo_acao_selic_rr,
        R.drawable.img_cielo_acao_selic_rr_rectangle,
    ),
    INTERACT_BANNER_OFFER_LUCKY_PROMO(
        R.drawable.img_promo_da_sorte_leaderboard_banner,
        R.drawable.img_promo_da_sorte_rectangle_banner,
    ),
    PORTAL_DE_NEGOCIACAO_COBRANCA_APP(
        R.drawable.img_portal_de_negociacao_cobranca_leaderboard_banner,
        R.drawable.img_portal_de_negociacao_cobranca_rectangle_banner,
    ),
    PRODUTO_RECARGA_CELULAR_SITE(
        R.drawable.img_produto_recarga_celular_site_leaderboard,
        R.drawable.img_produto_recarga_celular_site_rectangle,
    ),
    BANNER_ATUALIZACAO_CADASTRAL_APP(
        R.drawable.img_banner_atualizacao_cadastral_app_leaderboard,
        R.drawable.img_banner_atualizacao_cadastral_app_rectangle,
    ),
    BANNER_AUMENTO_VOLUME_BALCAO_PARLA_APP(
        R.drawable.img_banner_aumento_volume_balcao_parla_app_leaderboard,
        R.drawable.img_banner_aumento_volume_balcao_parla_app_rectangle,
    ),
    BANNER_AUMENTO_VOLUME_BALCAO_CALL_LINK_APP(
        R.drawable.img_banner_aumento_volume_balcao_call_leaderboard,
        R.drawable.img_banner_aumento_volume_balcao_call_rectangle,
    ),
    PORTAL_DE_NEGOCIACAO_COBRANCA_APP_EC_INATIVO(
        R.drawable.img_portal_de_negociacao_cobranca_inativo_leaderboard_banner,
        R.drawable.img_portal_de_negociacao_cobranca_inativo_rectangle_banner,
    ),
    CAPITAL_DE_GIRO_BB_APP(
        R.drawable.img_captal_giro_bb_leaderboard_banner,
        R.drawable.img_captal_giro_bb_rectangle_banner,
    ),
    ATENDIMENTO_WHATSAPP_APP(
        R.drawable.img_atendimento_whatsapp_leaderboard_banner,
        R.drawable.img_atendimento_whatsapp_rectangle_banner,
    ),
    OFERTA_BLACK_FRIDAY_ARV_APP(
        R.drawable.img_oferta_black_friday_arv_leaderboard_banner,
        R.drawable.img_oferta_black_friday_arv_rectangle_banner,
    ),
    OFERTA_BLACK_FRIDAY_RR_APP(
        R.drawable.img_oferta_black_friday_rr_leaderboard_banner,
        R.drawable.img_oferta_black_friday_rr_rectangle_banner,
    ),
    BANNER_DIRF_APP(
        R.drawable.img_dirf_app_leaderboard_banner,
        R.drawable.img_dirf_app_rectangle_banner,
    ),
    BANNER_VENDA_VIA_WPP_APP(
        R.drawable.img_oferta_vender_wpp_leaderboard_banner,
        R.drawable.img_oferta_vender_wpp_rectangle_banner,
    ),
    BANNER_P2M_APP(
        R.drawable.img_oferta_vender_wpp_leaderboard_banner,
        R.drawable.img_oferta_vender_wpp_rectangle_banner,
    ),
    BANNER_MFA_ARV_P1_APP(
        R.drawable.img_oferta_ative_token_arv_p1_leaderboard_banner,
        R.drawable.img_oferta_ative_token_arv_p1_rectangle_banner,
    ),
    BANNER_MFA_ARV_P2_APP(
        R.drawable.img_oferta_em_breve_ative_token_arv_p2_leaderboard_banner,
        R.drawable.img_oferta_em_breve_ative_token_arv_p2_rectangle_banner,
    ),
    RR_SEMANA_CONSUMIDOR_APP(
        R.drawable.img_rr_consumer_week_leaderboard_banner,
        R.drawable.img_rr_consumer_week_rectangle_banner,
    ),
    BANNER_ARV_APP(
        R.drawable.img_arv_app_leaderboard_banner,
        R.drawable.img_arv_app_rectangle_banner,
    ),
    BANNER_FAROL_CONTRATADO_APP(
        R.drawable.img_farol_contratado_app_leaderboard_banner,
        R.drawable.img_farol_contratado_app_rectangle_banner,
    ),
    BANNER_FAROL_APP(
        R.drawable.img_farol_app_new_leaderboard_banner,
        R.drawable.img_farol_app_new_rectangle_banner,
    ),
    PARCELADO_CLIENTE_APP(
        R.drawable.img_installment_app_leaderboard_banner,
        R.drawable.img_installment_app_rectangle_banner,
    ),
    CONVERSOR_DE_MOEDAS_APP(
        R.drawable.img_currency_converter_app_leaderboard_banner,
        R.drawable.img_currency_converter_app_rectangle_banner,
    ),
    PORTAL_DE_NEGOCIACAO_COBRANCA_DESCONTO_ATIVO_APP(
        R.drawable.img_discount_billing_app_leaderboard_banner,
        R.drawable.img_discount_billing_app_rectangle_banner,
    ),
    PORTAL_DE_NEGOCIACAO_COBRANCA_DESCONTO_INATIVO_APP(
        R.drawable.img_discount_billing_app_leaderboard_banner,
        R.drawable.img_discount_billing_app_rectangle_banner,
    ),
    BANNER_IDENTIDADE_DIGITAL_APP(
        R.drawable.img_digital_identity_app_leaderboard_banner,
        R.drawable.img_digital_identity_app_rectangle_banner,
    ),
    BANNER_PIX_APP(
        R.drawable.img_pix_app_new_leaderboard_banner,
        R.drawable.img_pix_app_new_rectangle_banner,
    ),
    BANNER_SUPERLINK_APP(
        R.drawable.img_superlink_app_leaderboard_banner,
        R.drawable.img_superlink_app_rectangle_banner,
    ),
    PORTAL_DE_NEGOCIACAO_PASCOA_APP(
        R.drawable.img_easter_negotiation_app_leaderboard_banner,
        R.drawable.img_easter_negotiation_app_rectangle_banner,
    ),
    BANNER_SUPERLINK_PASCOA_APP(
        R.drawable.img_superlink_easter_app_leaderboard_banner,
        R.drawable.img_superlink_easter_app_rectangle_banner,
    ),
    PRODUTO_RR_APP(
        R.drawable.img_product_rr_app_leaderboard_banner,
        R.drawable.img_product_rr_app_rectangle_banner,
    ),
    BANNER_INCENTIVO_PIX_APP(
        R.drawable.img_incentivo_pix_app_leaderboard_banner,
        R.drawable.img_incentivo_pix_app_rectangle_banner,
    ),
    BANNER_SUPERLINK_DIA_DAS_MAES_APP(
        R.drawable.img_super_link_dia_das_maes_app_leaderboard_banner,
        R.drawable.img_super_link_dia_das_maes_app_rectangle_banner,
    ),
    OFERTA_PARA_LP_P2M_APP(
        R.drawable.img_oferta_vender_whats_app_rr_leaderboard_banner,
        R.drawable.img_oferta_vender_whats_app_retangle_banner,
    ),
    BANNER_DIA_DOS_PAIS_ARV_APP(
        R.drawable.img_oferta_dia_dos_pais_arv_leaderboard,
        R.drawable.img_oferta_dia_dos_pais_arv_rectangle,
    ),
    BANNER_DIA_DOS_PAIS_RR_APP(
        R.drawable.img_oferta_dia_dos_pais_rr_leaderboard,
        R.drawable.img_oferta_dia_dos_pais_rr_rectangle,
    ),
    BANNER_DIA_DOS_PAIS_SUPERLINK_APP(
        R.drawable.img_oferta_dia_dos_pais_superlink_leaderboard,
        R.drawable.img_oferta_dia_dos_pais_superlink_rectangle,
    ),
    BANNER_RR_SEGMENTADO_BAU_APP(
        R.drawable.img_oferta_segmentado_rr_leaderboard,
        R.drawable.img_oferta_segmentado_rr_rectangle,
    ),
    BANNER_MANUTENCAO_PREDITIVA(
        R.drawable.img_predictive_battery_leaderboard_banner,
        R.drawable.img_predictive_battery_rectangle_banner,
    ),
    REATIVACAO_MDR_ALUGUEL_99(
        R.drawable.img_mdr_offer_leaderboard_banner,
        R.drawable.img_mdr_offer_rectangle_banner,
    ),
    REATIVACAO_MDR_RR_ALUGUEL_99(
        R.drawable.img_mdr_offer_leaderboard_banner,
        R.drawable.img_mdr_offer_rectangle_banner,
    ),
    RETENCAO_MDR_ALUGUEL_129(
        R.drawable.img_mdr_offer_leaderboard_banner,
        R.drawable.img_mdr_offer_rectangle_banner,
    ),
    RETENCAO_MDR_RR_ALUGUEL_129(
        R.drawable.img_mdr_offer_leaderboard_banner,
        R.drawable.img_mdr_offer_rectangle_banner,
    ),
    RETENCAO_MDR_ALUGUEL_S_POSTECIPADO(
        R.drawable.img_mdr_offer_leaderboard_banner,
        R.drawable.img_mdr_offer_rectangle_banner,
    ),
    RETENCAO_MDR_ALUGUEL_RR_S_POSTECIPADO(
        R.drawable.img_mdr_offer_leaderboard_banner,
        R.drawable.img_mdr_offer_rectangle_banner,
    ),
    RETENCAO_MDR_S_MAQUINA(
        R.drawable.img_mdr_offer_leaderboard_banner,
        R.drawable.img_mdr_offer_rectangle_banner,
    ),
    RETENCAO_MDR_RR_S_MAQUINA(
        R.drawable.img_mdr_offer_leaderboard_banner,
        R.drawable.img_mdr_offer_rectangle_banner,
    ),
    BANNER_MVP_RECUPERACAODEATIVOS_NA_APP(
        R.drawable.img_mvp_recovery_of_assets_leaderboard_banner,
        R.drawable.img_mvp_recovery_of_assets_rectangle_banner,
    ),
    BANNER_PIX_POSTECIPADO_NA_APP(
        R.drawable.img_pix_postponed_leaderboard_banner,
        R.drawable.img_pix_postponed_rectangle_banner,
    ),
    BANNER_CIELOTAP_FOMENTO_NA_APP(
        R.drawable.img_cielo_tap_promotion_leaderboard_banner,
        R.drawable.img_cielo_tap_promotion_rectangle_banner,
    ),
    BANNER_PIX_TAXAZERO_NA_APP(
        R.drawable.img_pix_zero_rate_leaderboard_banner,
        R.drawable.img_pix_zero_rate_rectangle_banner,
    ),
    BANNER_PIX_DIA_DAS_MAES_NA_APP(
        R.drawable.img_pix_mothers_day_leaderboard_banner,
        R.drawable.img_pix_mothers_day_rectangle_banner,
    ),
    BANNER_ARV_OFERTA_CRISE_NA_APP(
        R.drawable.img_arv_supply_crisis_leaderboard_banner,
        R.drawable.img_arv_supply_crisis_rectangle_banner,
    ),
    BANNER_LINK_DE_PAGAMENTO_LIBERADO_NA_APP(
        R.drawable.img_link_de_pagamento_liberado_na_app_leaderboard_banner,
        R.drawable.img_link_de_pagamento_liberado_na_app_rectangle_banner,
    ),
    BANNER_TAP_MENSALIDADE_ZERO_NA_APP(
        R.drawable.img_cielo_tap_zero_monthly_fee_leaderboard_banner,
        R.drawable.img_cielo_tap_zero_monthly_fee_rectangle_banner,
    ),
    BANNER_ACOMPANHAMENTO_PEDIDOMAQUINA_NA_APP(
        R.drawable.img_machine_tracking_leaderboard_banner,
        R.drawable.img_machine_tracking_rectangle_banner
    ),
    RA_D1_BASE_COM_PRODUTO(
        R.drawable.img_product_rr_app_leaderboard_banner,
        R.drawable.img_product_rr_app_rectangle_banner,
    )
}
