package br.com.mobicare.cielo.biometricToken.constants

object BiometricTokenConstants {
    const val ARG_BIOMETRIC_TOKEN_SELFIE_SCREEN = "ARG_BIOMETRIC_TOKEN_SELFIE_SCREEN"
    const val ARG_BIOMETRIC_SELFIE_SDK = "ARG_BIOMETRIC_SELFIE_SDK"
    const val ARG_BIOMETRIC_USERNAME = "ARG_BIOMETRIC_USERNAME"
    const val ARG_BIOMETRIC_TOKEN = "ARG_BIOMETRIC_TOKEN"
    const val ARG_BIOMETRIC_SCREEN_NAME = "ARG_BIOMETRIC_SCREEN_NAME"
    const val ARG_BIOMETRIC_SCREEN_NAME_EXCEPTION = "ARG_BIOMETRIC_SCREEN_NAME_EXCEPTION"
    const val ARG_BIOMETRIC_SCREEN_NAME_GENERIC_ERROR = "ARG_BIOMETRIC_SCREEN_NAME_EXCEPTION"
    const val ARG_BIOMETRIC_IS_LOGIN_FLOW = "ARG_BIOMETRIC_IS_LOGIN_FLOW"
    const val STONEAGE = "STONEAGE"
}