package br.com.mobicare.cielo.arv.analytics

object ArvAnalyticsGA4Constants {
    private const val CONFIGURATION = "configuracao"
    private const val CONFIRMATION = "confirmacao"
    private const val SIMULATOR = "simulador"
    const val ANTICIPATION_PERIOD_VALUE = "antecipar_valor_do_periodo"
    const val ARV = "arv"
    const val ARV_TRUNK = "arv_bau"
    const val SINGLE = "avulsa"
    const val SIMULATE = "simular"
    const val ARV_AUTOMATIC_BASE = "t_arv_automatica."
    const val ARV_SINGLE_BASE = "t_arv_avulsa."
    const val ANTICIPATIONS = "antecipacoes"
    const val AUTOMATIC = "automatica"
    const val BUTTON = "button"
    const val KNOW_MORE_BTN = "saiba_mais"
    const val CONTRACTING = "contratacao"
    const val SIMULATE_VALUE = "simular_valor"
    const val ADD = "adicionar"
    const val SEND = "enviar"
    const val MODAL_RANGE = "modal_faixa"
    const val REMOVE = "remover"
    const val NO_BALANCE_AVAILABLE = "sem_saldo_disponivel"
    const val INSUFFICIENT_FUNDS = "saldo_insuficiente"
    private const val INTRODUCTION = "introducao"
    const val HOME = "home"
    private const val FLAG_SELECTION = "selecao_bandeira"
    private const val OPTIN = "optin"
    private const val SUCCESS = "sucesso"
    const val PARTNER_AUTHORIZATION = "autorizacao_de_parceiros"
    const val REALIZE_AUTHORIZATION_OPTIN = "realizar_autorizacao_optin"
    const val REALIZE_AUTHORIZATION = "realizar_autorizacao"
    private const val CANCEL = "cancelamento"
    const val CANCEL_ANTICIPATION = "cancelar_antecipacao"
    private const val REASONS = "motivos"
    private const val HISTORIC = "historico"
    private const val DETAILS = "detalhes"
    const val SCREEN_VIEW_ARV_AUTOMATIC_CONFIGURATION = "/$ARV/$AUTOMATIC/$CONFIGURATION"
    const val SCREEN_VIEW_ARV_AUTOMATIC_CONFIRMATION = "/$ARV/$AUTOMATIC/$CONFIRMATION"
    const val SCREEN_VIEW_ARV_AUTOMATIC_SUCCESS = "/$ARV/$AUTOMATIC/$SUCCESS"
    const val SCREEN_VIEW_ARV = "/$ARV"
    const val SCREEN_VIEW_ARV_INTRODUCTION = "/$ARV/$INTRODUCTION"
    const val SCREEN_VIEW_ARV_OPTIN = "/$ARV/$OPTIN"
    const val SCREEN_VIEW_ARV_OPTIN_PARTNER_AUTHORIZATION =
        "/$ARV/$OPTIN/${PARTNER_AUTHORIZATION}"
    const val SCREEN_VIEW_ARV_SINGLE_CONFIGURATION = "/$ARV/$SINGLE/$CONFIGURATION"
    const val SCREEN_VIEW_ARV_SINGLE_CONFIRMATION = "/$ARV/$SINGLE/$CONFIRMATION"
    const val SCREEN_VIEW_ARV_SINGLE_CONFIGURATION_SIMULATOR =
        "/$ARV/$SINGLE/$CONFIGURATION/$SIMULATOR"
    const val SCREEN_VIEW_ARV_SINGLE_CONFIRMATION_FLAG_SELECTION =
        "/$ARV/$SINGLE/$CONFIRMATION/${FLAG_SELECTION}"
    const val SCREEN_VIEW_ARV_SINGLE_SUCCESS = "/$ARV/$SINGLE/$SUCCESS"
    const val SCREEN_VIEW_ARV_CANCEL = "/$ARV/$CANCEL"
    const val SCREEN_VIEW_ARV_CANCEL_REASONS = "/$ARV/$CANCEL/$REASONS"
    const val SCREEN_VIEW_ARV_CANCEL_SUCCESS = "/$ARV/$CANCEL/$SUCCESS"
    const val SCREEN_VIEW_ARV_HISTORIC = "/$ARV/$HISTORIC"
    const val SCREEN_VIEW_ARV_HISTORIC_DETAILS = "/$ARV/$HISTORIC/$DETAILS"
    const val SCREEN_VIEW_HOME_ARV_MODAL_RANGE = "/$HOME/$ARV/$MODAL_RANGE"
}
