package br.com.mobicare.cielo.commons.enums

enum class MfaStatusEnums(val mfaStatus: String) {
    OTP_REQUIRED("OTP_REQUIRED"),
    OTP_ENROLLMENT_REQUIRED("OTP_ENROLLMENT_REQUIRED"),
    OTP_ENROLLMENT_PENDING("OTP_ENROLLMENT_PENDING"),
    OTP_ENROLLMENT_EXPIRED("OTP_ENROLLMENT_EXPIRED"),
    OTP_TEMPORARILY_BLOCKED("OTP_TEMPORARILY_BLOCKED"),
    NOT_ELIGIBLE("NOT_ELIGIBLE"),
    INVALID_OTP_CODE("INVALID_OTP_CODE");
}
