package br.com.mobicare.cielo.pix.enums

enum class PixLimitTypeEnum {
    DAYTIME_TRANSACTION_LIMIT,
    TOTAL_DAYTIME_TRANSACTION_LIMIT,
    TOTAL_MONTH_TRANSACTION_LIMIT,
    TOTAL_NIGHTTIME_TRANSACTION_LIMIT,
    NIGHTTIME_TRANSACTION_LIMIT
}