package br.com.mobicare.cielo.meuCadastroDomicilio

const val MEU_CADASTRO_DOMICILIO_BANKS = "MEU_CADASTRO_DOMICILIO_BANKS"
const val MEU_CADASTRO_DOMICILIO_DESTINATION = "MEU_CADASTRO_DOMICILIO_DESTINATION"
const val MEU_CADASTRO_DOMICILIO_ORIGIN = "MEU_CADASTRO_DOMICILIO_ORIGIN"