package br.com.mobicare.cielo.idOnboarding.analytics.constants

const val ANALYTICS_ID_SCREEN_VIEW_ALERT_UPADTE_DATA_30_DAYS = "/identidade digital/atualizar dados em ate 30 dias"
const val ANALYTICS_ID_SCREEN_VIEW_ALERT_UPADTE_DATA_5_DAYS = "/identidade digital/atualizar dados em ate 5 dias"
const val ANALYTICS_ID_SCREEN_VIEW_ALERT_UPADTE_EXPIRED = "/identidade digital/o prazo para atualizar os dados expirou"
const val ANALYTICS_ID_SCREEN_VIEW_ALERT_UPADTE_CONTINUE = "/identidade digital/que bom te ver aqui de novo"
const val ANALYTICS_ID_SCREEN_VIEW_ALERT_UPADTE_CONTINUE_MANDATORY = "/identidade digital/atualizar dados para acessar a conta"
const val ANALYTICS_ID_SCREEN_VIEW_COMPLETE_PROFILE_SETUP = "/identidade digital/concluir configuracao do perfil/"
const val ANALYTICS_ID_SCREEN_VIEW_CUSTOMER_RETENTION = "/identidade digital/retencao do cliente"
const val ANALYTICS_ID_SCREEN_VIEW_DOCUMENT_YOU_WANT_TO_SEND = "/identidade digital/documento que deseja enviar"
const val ANALYTICS_ID_SCREEN_VIEW_TIPS_FOR_A_GOOD_PHOTO = "/identidade digital/dicas para uma boa foto/"
const val ANALYTICS_ID_SCREEN_VIEW_TIPS_FOR_A_GOOD_SELFIE = "/identidade digital/dicas para uma boa selfie"
const val ANALYTICS_ID_SCREEN_VIEW_VALIDATE_P2 = "/identidade digital/validar identidade do usuario final da p2"

const val ANALYTICS_ID_REMEMBER_UPDATE_DATA_30_DAYS = "atualizar dados em ate 30 dias"
const val ANALYTICS_ID_REMEMBER_UPDATE_DATA_5_DAYS = "atualizar dados em ate 5 dias"
const val ANALYTICS_ID_REMEMBER_UPDATE_EXPIRED = "o prazo para atualizar os dados expirou"
const val ANALYTICS_ID_REMEMBER_UPDATE_CONTINUE = "que bom te ver aqui de novo"
const val ANALYTICS_ID_REMEMBER_UPDATE_CONTINUE_MANDATORY = "atualizar dados para acessar a conta"

const val ANALYTICS_ID_REMEMBER_SEND_PHOTOS = "lembrete de envio da foto"

const val ANALYTICS_ID_CUSTOMER_RETENTION = "retencao do cliente"
const val ANALYTICS_ID_COMPLETE_CONFIGURATION = "concluir configuracao do perfil"
const val ANALYTICS_ID_ACCESS_HELP_CENTER = "acessar a central de ajuda"
const val ANALYTICS_ID_BTN_SEND_PICTURES_LATER= "enviar foto depois"
const val ANALYTICS_ID_BTN_SEND_PICTURES = "enviar foto agora"
const val ANALYTICS_ID_BTN_COME_BACK = "voltar"
const val ANALYTICS_ID_BTN_DO_LATER = "fazer mais tarde"
const val ANALYTICS_ID_BTN_TRY_AGAIN = "tentar novamente"
const val ANALYTICS_ID_PICTURE_NOT_VALIDATE = "nao conseguimos validar sua foto"
const val ANALYTICS_ID_PICTURE_SENT_FOR_REVIEW = "fotos enviadas para analise aguarde"

const val ANALYTICS_ID_DOCUMENT_YOU_WANT_TO_SEND = "documento que deseja enviar"
const val ANALYTICS_ID_DOCUMENT = "documento"
const val ANALYTICS_ID_CNH = "cnh"
const val ANALYTICS_ID_RG = "rgmodeloantigo"
const val ANALYTICS_ID_NEW_RG = "novorg"

const val ANALYTICS_ID_TIPS_DOCUMENT_PICTURES = "dicas para uma boa foto"
const val ANALYTICS_ID_VALIDATE = "validar"
const val ANALYTICS_ID_ERROR_BR_SCAN = "erro no sdk da br scan"

const val ANALYTICS_ID_TIPS_SELFIE = "dicas para uma boa selfie"
const val ANALYTICS_ID_OPEN_CAMERA = "abrir camera"
const val ANALYTICS_ID_VALIDATE_SELFIE = "validar selfie"
const val ANALYTICS_ID_ERROR_UNICO = "erro no sdk da unico"

const val ANALYTICS_ID_VALIDATE_P2 = "validar identidade do usuario final da p2"
const val ANALYTICS_ID_MODAL_ERROR = "algo deu errado"
const val ANALYTICS_ID_MODAL_SUCCESS = "dados enviados para analise"

const val ANALYTICS_ID_ERROR_VALIDATE_IDENTITY = "nao foi possivel validar identidade"
const val ANALYTICS_ID_ERROR_VALIDATE_IDENTITY_BTN = "tirar novas fotos"

const val ANALYTICS_ID_GENERIC_ERROR = "500"

//GA
const val ANALYTICS_ID_SCREEN_VIEW_SEND_PICTURES = "/id_digital/p2/enviar_fotos"
const val ANALYTICS_ID_SCREEN_VIEW_SEND_PICTURES_ADMIN = "/id_digital/analyst_p2/enviar_fotos"
const val ANALYTICS_ID_SCREEN_VIEW_SEND_PICTURES_ANALYST = "/id_digital/admin_p2/enviar_fotos"
const val ANALYTICS_ID_SCREEN_VIEW_SEND_PICTURES_TECHNICAL = "/id_digital/technical_p2/enviar_fotos"
const val ANALYTICS_ID_SCREEN_VIEW_SEND_PICTURES_SEND_LATER = "/id_digital/p2/enviar_fotos/enviar_fotos_depois"
const val ANALYTICS_ID_SCREEN_VIEW_SELECT_DOCUMENT_TYPE = "/id_digital/p2/selecionar_tipo_de_documento"
const val ANALYTICS_ID_SCREEN_VIEW_SELECT_DOCUMENT_GUIDE_CNH = "/id_digital/p2/selecionar_tipo_de_documento/cnh/dicas_para_fotos_do_documento"
const val ANALYTICS_ID_SCREEN_VIEW_SELECT_DOCUMENT_GUIDE_RG = "/id_digital/p2/selecionar_tipo_de_documento/rg/dicas_para_fotos_do_documento"
const val ANALYTICS_ID_SCREEN_VIEW_SELECT_DOCUMENT_GUIDE_NEW_RG = "/id_digital/p2/selecionar_tipo_de_documento/novo_rg/dicas_para_fotos_do_documento"
const val ANALYTICS_ID_SCREEN_VIEW_PHOTOGRAPH_RG = "/id_digital/p2/fotografar_rg"
const val ANALYTICS_ID_SCREEN_VIEW_PHOTOGRAPH_CNH = "/id_digital/p2/fotografar_cnh"
const val ANALYTICS_ID_SCREEN_VIEW_SELFIE = "/id_digital/p2/selfie"
const val ANALYTICS_ID_SCREEN_VIEW_SELFIE_TIPS = "/id_digital/p2/selfie/dicas"
const val ANALYTICS_ID_SCREEN_VIEW_DOCUMENTS_SENT = "/id_digital/p2/documentos_enviados"
const val ANALYTICS_ID_SCREEN_VIEW_DOCUMENTS_SENT_SUCCESS = "/id_digital/p2/documentos_enviados/sucesso"
const val ANALYTICS_ID_SCREEN_VIEW_DOCUMENTS_SENT_ANALYSIS = "/id_digital/p2/documentos_enviados/em_analise"
const val ANALYTICS_ID_SCREEN_VIEW_ERROR_VALIDATE_YOUR_IDENTITY = "/login/id_digital/p2/nao_foi_possivel_validar_sua_identidade"
const val ANALYTICS_ID_SCREEN_VIEW_HOME_ID_P2 = "/home/id_digital/p2/analise/sucesso"
const val ANALYTICS_ID_MODAL_TIPS_TO_PICTURES_DOCUMENT = "modal_dicas_para_fotos_do_documento"
const val ANALYTICS_ID_TIPS_TO_PICTURES_DOCUMENT = "dicas_para_fotos_do_documento"
const val ANALYTICS_ID_FOLLOW_TIPS_TO_GOOD_PICTURE = "siga_essas_dicas_para_tirar_uma_boa_foto"
const val ANALYTICS_ID_TRY_AGAIN_INSTRUCTIONS = "instrucoes_realizando_etapa_novamente"
const val ANALYTICS_ID_MODAL_TRY_AGAIN_INSTRUCTIONS = "modal_instrucoes_realizando_etapa_novamente"
const val ANALYTICS_ID_SEND_PICTURES_NOW = "enviar_fotos_agora"
const val ANALYTICS_ID_SEND_PICTURES_LATER = "enviar_fotos_depois"
const val ANALYTICS_ID_SEND_PICTURES_LATER_MESSAGE = "ao_deixar_de_efetuar_essa_etapa_seu_acesso_sera_limitado"
const val ANALYTICS_ID_CNH_SELECTED = "documento_cnh_selecionado"
const val ANALYTICS_ID_RG_SELECTED = "documento_rg_selecionado"
const val ANALYTICS_ID_NEW_RG_SELECTED = "documento_novo_rg_selecionado"
const val ANALYTICS_ID_TIPS_TO_SELFIE = "dicas_para_selfie"
const val ANALYTICS_ID_FACE_PICTURE = "vamos_tirar_uma_foto_do_seu_rosto"
const val ANALYTICS_GENERIC_ERROR = "erro_generico"
const val ANALYTICS_ERROR_VALIDATE_PICTURE = "erro_ao_validar_foto"
const val ANALYTICS_ID_DATA_SENT_FOR_ANALYSIS = "dados_enviados_para_analise"
const val ANALYTICS_ID_WAIT_TO_VALIDATE = "essa_validacao_pode_demorar_um_pouco"
const val ANALYTICS_ID_WAIT_FEW_MINUTES_TO_VALIDATE = "essa_validacao_pode_demorar_alguns_minutos"
const val ANALYTICS_ID_SOON_ACCESS = "em_breve_voce_tera_acesso_a_todas_as_funcionalidades_do_app"
const val ANALYTICS_ID_ERROR_VALIDATE_YOUR_IDENTITY = "nao_foi_possivel_validar_sua_identidade"
const val ANALYTICS_ID_SEND_ALL_PHOTOS = "envie_novas_fotos_do_seu_rosto_e_documento_para_aproveitar_todas_as_funcionalidades_do_app_cielo_gestao"
const val ANALYTICS_ID_WELCOME_ACCESS = "aproveite_a_gestao_de_acessos_e_todas_as_funcoes_do_seu_app"
const val ANALYTICS_ID_ALL_READY = "tudo_pronto"
const val ANALYTICS_ID_SUCCESS_IN_DATA_ANALYSIS = "sucesso_na_analise_dos_dados"
const val ANALYTICS_ID_VALIDATE_P2_ERROR = "erro_ao_validar_p2"
const val APPSFLYER_AF_CONTENT_TYPE = "af_content_type"
const val APPSFLYER_MODAL = "modal"
const val APPSFLYER_AF_SCREEN_NAME = "af_screen_name"
const val APPSFLYER_AF_DISPLAY_CONTENT = "af_display_content"